# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d64917a6456bf9526e8eb417cd7e80503016e2fb8fbd28249e170fdee00aad0007b5d2c7a346ee4affb140aad05ea90a869de9fa4861d4d9a233907710eafc8a

test:
  secret_key_base: d729ea97b60be32c17bb02874627e57ba49e9c9d844f8a99580a0e19899693b820b1e4c0b63dc7ee36e95f1fefad8351c0ebbe5927bda2b3794a6693a9b8ff99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
